baseURL = "https://v2.docs.influxdata.com/"
title = "InfluxDB Documentation"
languageCode = "en-us"
DefaultContentLanguage = "zh"

# Git history information for lastMod-type functionality
enableGitInfo = true

# Syntax Highlighting
pygmentsCodefences = true
pygmentsUseClasses = true

# Preserve case in article tags
preserveTaxonomyNames = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 2
  [languages.zh]
    languageName = "中文"
    weight = 1

# Markdown rendering options
[blackfriday]
hrefTargetBlank = true
smartDashes = false

[taxonomies]
  "v2.0/tag" = "v2.0/tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
